version: "3.9"
services:
  db:
    image: mysql:5.7.40
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'M4r10test'
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: 'veeva'
      MYSQL_PASSWORD: 'H45l0'
    ports:
      - '13306:3306'
    expose:
      - '13306'
    volumes:
      - /Users/mariuszjurgielewicz/src/veeva/veevacrm/db_backups:/tmp/backup
      - './.mysql-data/db:/var/lib/mysql'

# for WebUI
  adminer:
    image: adminer:4.8.1
    ports:
      - "8088:8080"