version: "3.9"
services:
  db:
    image: mysql:8.0.32
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'M4r10test'
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3308:3306'
    expose:
      - '3308'
    volumes:
      - './.mysql-data/db:/var/lib/mysql'

# for WebUI
  adminer:
    image: adminer:4.8.1
    ports:
      - "8088:8080"