version: "3.8"        # a more current version
services:
  drill:
    image: apache/drill:latest
    volumes:
      - /tmp:/tmp     # for keeping plugin configuration changes
    ports:
      - "8047:8047"
    stdin_open: true  # add this line
                      # do not override entrypoint: or command: