version: "3"
services:
  db:
    image: "postgres:11"
    container_name: "local_postgres"
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data
volumes:
  database_data: